//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Burza
    {
        public int BurzaID { get; set; }
        public int DzienID { get; set; }
        public int Punkty_wiatr { get; set; }
        public int Punkty_deszcz { get; set; }
        public int Punkty_grad { get; set; }
        public int Punkty_wyladowania { get; set; }
        public string Kierunek_frontu { get; set; }
        public System.TimeSpan Czas_poczatku { get; set; }
        public Nullable<System.TimeSpan> Czas_konca { get; set; }
        public string Opis { get; set; }
    
        public virtual Dzien Dzien { get; set; }
    }
}
