//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherBaseEntities : DbContext
    {
        public WeatherBaseEntities()
            : base("name=WeatherBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Burza> Burza { get; set; }
        public virtual DbSet<Dzien> Dzien { get; set; }
        public virtual DbSet<Opady_deszczu> Opady_deszczu { get; set; }
        public virtual DbSet<Opady_sniegu> Opady_sniegu { get; set; }
        public virtual DbSet<Pokrywa_sniezna> Pokrywa_sniezna { get; set; }
        public virtual DbSet<Stan_zachmurzenia> Stan_zachmurzenia { get; set; }
        public virtual DbSet<Temperatura> Temperatura { get; set; }
        public virtual DbSet<Wiatr> Wiatr { get; set; }
    }
}
