//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokrywa_sniezna
    {
        public int DzienID { get; set; }
        public int Grubosc { get; set; }
        public string Typ_sniegu { get; set; }
    
        public virtual Dzien Dzien { get; set; }

    }
}
