//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stan_zachmurzenia
    {
        public int DzienID { get; set; }
        public string Pora_dnia { get; set; }
        public string Wielkosc_zachmurzenia { get; set; }
        public string Typ_chmur { get; set; }
    
        public virtual Dzien Dzien { get; set; }
    }
}
